Makefile; Indentation; Spell-checking
* Add more helpful docs (for me at least :-)) to the Makefile
* Re-default to tab indentation shown as four spaces by default
* Explicitly make Python files use 4-space indentation
* Fix auto-done indentation in mklatex
* Fix spacing between sections in my vimrc
* Add spell-checking to text and HTML files
* Use filetypes more than extensions for KISSing

diff --git a/bin/mklatex b/bin/mklatex
--- a/bin/mklatex
+++ b/bin/mklatex
@@ -24,199 +24,199 @@ QUIET=0
 
 function mkl_checkreturn()
 {
-    if [ $? != 0 ]; then
-        echo "ERROR!  There has been an error; exiting..."
-        if [ $WASDTX == 1 ]; then
-            lacheck $FILE.dtx
-        else
-            lacheck $FILE
-        fi
-        exit 42
-    fi
+	if [ $? != 0 ]; then
+		echo "ERROR!  There has been an error; exiting..."
+		if [ $WASDTX == 1 ]; then
+			lacheck $FILE.dtx
+		else
+			lacheck $FILE
+		fi
+		exit 42
+	fi
 }
 
 function mkl_usage()
 {
-    echo "Compile a LaTeX document and/or clean up the results."
-    echo
-    echo "Usage: mklatex [-q] [<file>.(tex|dtx)] [-k|-l]"
-    echo "    -q     -- ultra-quiet mode (don't use until sure!)"
-    echo "    <file> -- Name of file to compile.  The .tex extension is"
-    echo "              not needed.  If not specified, the name of the"
-    echo "              current directory will be used instead."
-    echo "              NB: All files with cleanup suffixes (see below)"
-    echo "                  in the current directory will be removed in"
-    echo "                  this case."
-    echo "    -k     -- Keep temporary and log files."
-    echo "    -l     -- Keep just the log file."
-    echo
-    echo "Alternative usage: ltcleanup [-l]"
-    echo "    -l -- don't remove the log file"
-    echo "    Remove files with suffixes as follows"
-    echo "        $SUFFIXES1"
-    echo "        $SUFFIXES2"
-    echo "    it will also remove *-blx.bib (generated by biblatex)."
-    echo
-    echo "This script requires that the glossaries package is installed"
-    echo "and that makeglossaries is on the current path."
+	echo "Compile a LaTeX document and/or clean up the results."
+	echo
+	echo "Usage: mklatex [-q] [<file>.(tex|dtx)] [-k|-l]"
+	echo "    -q     -- ultra-quiet mode (don't use until sure!)"
+	echo "    <file> -- Name of file to compile.  The .tex extension is"
+	echo "              not needed.  If not specified, the name of the"
+	echo "              current directory will be used instead."
+	echo "              NB: All files with cleanup suffixes (see below)"
+	echo "                  in the current directory will be removed in"
+	echo "                  this case."
+	echo "    -k     -- Keep temporary and log files."
+	echo "    -l     -- Keep just the log file."
+	echo
+	echo "Alternative usage: ltcleanup [-l]"
+	echo "    -l -- don't remove the log file"
+	echo "    Remove files with suffixes as follows"
+	echo "        $SUFFIXES1"
+	echo "        $SUFFIXES2"
+	echo "    it will also remove *-blx.bib (generated by biblatex)."
+	echo
+	echo "This script requires that the glossaries package is installed"
+	echo "and that makeglossaries is on the current path."
 }
 
 function mkl_docompile_pdflatex()
 {
-    if [[ -r $FILE.dtx ]]; then
-        pdflatex $FILE.dtx
-        RETVAL=$?
-        WASDTX=1
-    else
-        pdflatex $FILE
-        RETVAL=$?
-    fi
-    return $RETVAL
+	if [[ -r $FILE.dtx ]]; then
+		pdflatex $FILE.dtx
+		RETVAL=$?
+		WASDTX=1
+	else
+		pdflatex $FILE
+		RETVAL=$?
+	fi
+	return $RETVAL
 }
 
 function mkl_docompile_mp()
 {
-    echo METAPOST
-    ls *.mp > /dev/null 2> /dev/null
-    RETVAL=$?
-    if [ $RETVAL == 0 ]; then
-        for mpfile in *.mp; do
-            mpost $mpfile || exit 42
-        done
-    else
-        echo It seems there are no .mp files here.
-    fi
+	echo METAPOST
+	ls *.mp > /dev/null 2> /dev/null
+	RETVAL=$?
+	if [ $RETVAL == 0 ]; then
+		for mpfile in *.mp; do
+			mpost $mpfile || exit 42
+		done
+	else
+		echo It seems there are no .mp files here.
+	fi
 }
 
 function mkl_docompile_eps()
 {
-    echo EPSTOPDF
-    ls *.eps > /dev/null 2> /dev/null
-    RETVAL=$?
-    if [ $RETVAL == 0 ]; then
-        for epsfile in *.eps; do
-            if [ ! -f "$(basename -s .eps $epsfile).pdf" ]; then
-                $ECHO -n "$epsfile: " ; epstopdf $epsfile || exit 42 ; echo "done"
-            else
-                echo PDF of $epsfile already exists.
-            fi
-        done
-    else
-        echo It seems there are no .eps files here.
-    fi
+	echo EPSTOPDF
+	ls *.eps > /dev/null 2> /dev/null
+	RETVAL=$?
+	if [ $RETVAL == 0 ]; then
+		for epsfile in *.eps; do
+			if [ ! -f "$(basename -s .eps $epsfile).pdf" ]; then
+				$ECHO -n "$epsfile: " ; epstopdf $epsfile || exit 42 ; echo "done"
+			else
+				echo PDF of $epsfile already exists.
+			fi
+		done
+	else
+		echo It seems there are no .eps files here.
+	fi
 }
 
 function mkl_docompile()
 {
-    echo "Going to make $FILE..."
-    echo "Use the -h|--help option for more information."
-    echo
-    mkl_docompile_mp
-    echo
-    # FIXME remove when get mactex 2009
-    mkl_docompile_eps
-    echo
-    echo PDFLaTeX 1
-    mkl_docompile_pdflatex
-    mkl_checkreturn
-    echo
-    echo BibTeX
-    # compatible with multibib...
-    for BIBFILE in *.aux ; do
-        bibtex $(basename $BIBFILE .aux)
-    done
-    if [[ $? != 0 ]]; then
-        BIB='false'
-    fi
-    echo
-    # make glossaries?
-    if [ -r $FILE.glo ]; then
-        echo makeglossaries 1
-        if [ $QUIET == 1 ]; then
-            makeglossaries $FILE 2> /dev/null
-        else
-            makeglossaries $FILE
-        fi
-        mkl_checkreturn
-        echo
-    fi
-    echo PDFLaTeX 2
-    mkl_docompile_pdflatex > /dev/null
-    mkl_checkreturn
-    echo
-    echo PDFLaTeX 3
-    mkl_docompile_pdflatex > /dev/null
-    mkl_checkreturn
-    echo
-    # update glossaries and PDF?
-    if [ -r $FILE.glo ]; then
-        echo makeglossaries 2
-        makeglossaries $FILE > /dev/null 2> /dev/null
-        mkl_checkreturn
-        echo
-        echo PDFLaTeX 4
-        mkl_docompile_pdflatex > /dev/null
-        mkl_checkreturn
-        echo
-    fi
+	echo "Going to make $FILE..."
+	echo "Use the -h|--help option for more information."
+	echo
+	mkl_docompile_mp
+	echo
+	# FIXME remove when get mactex 2009
+	mkl_docompile_eps
+	echo
+	echo PDFLaTeX 1
+	mkl_docompile_pdflatex
+	mkl_checkreturn
+	echo
+	echo BibTeX
+	# compatible with multibib...
+	for BIBFILE in *.aux ; do
+		bibtex $(basename $BIBFILE .aux)
+	done
+	if [[ $? != 0 ]]; then
+		BIB='false'
+	fi
+	echo
+	# make glossaries?
+	if [ -r $FILE.glo ]; then
+		echo makeglossaries 1
+		if [ $QUIET == 1 ]; then
+			makeglossaries $FILE 2> /dev/null
+		else
+			makeglossaries $FILE
+		fi
+		mkl_checkreturn
+		echo
+	fi
+	echo PDFLaTeX 2
+	mkl_docompile_pdflatex > /dev/null
+	mkl_checkreturn
+	echo
+	echo PDFLaTeX 3
+	mkl_docompile_pdflatex > /dev/null
+	mkl_checkreturn
+	echo
+	# update glossaries and PDF?
+	if [ -r $FILE.glo ]; then
+		echo makeglossaries 2
+		makeglossaries $FILE > /dev/null 2> /dev/null
+		mkl_checkreturn
+		echo
+		echo PDFLaTeX 4
+		mkl_docompile_pdflatex > /dev/null
+		mkl_checkreturn
+		echo
+	fi
 
-    # Errors and warnings...
-    if [[ -r $FILE.log ]]; then
-        echo ERRORS and WARNINGS:
-        grep -i '\(error\)\|\(warn\)' $FILE.log
-    else
-        echo No log file created???
-    fi
+	# Errors and warnings...
+	if [[ -r $FILE.log ]]; then
+		echo ERRORS and WARNINGS:
+		grep -i '\(error\)\|\(warn\)' $FILE.log
+	else
+		echo No log file created???
+	fi
 
-    # Cleanup...
-    echo
-    if [[ $KOPT == '-k' ]]; then
-        echo Not removing temporary and log files...
-    else
-        if [[ $KOPT == '-l' ]]; then
-            mkl_ltcleanup -l
-        else
-            mkl_ltcleanup
-        fi
-        mkl_checkreturn
-    fi
+	# Cleanup...
+	echo
+	if [[ $KOPT == '-k' ]]; then
+		echo Not removing temporary and log files...
+	else
+		if [[ $KOPT == '-l' ]]; then
+			mkl_ltcleanup -l
+		else
+			mkl_ltcleanup
+		fi
+		mkl_checkreturn
+	fi
 
-    # BibTeX failure notice...
-    if [[ $BIB == 'false' ]]; then
-        echo
-        echo "BibTeX had errors; possibly due to the document having no references."
-    fi
+	# BibTeX failure notice...
+	if [[ $BIB == 'false' ]]; then
+		echo
+		echo "BibTeX had errors; possibly due to the document having no references."
+	fi
 }
 
 function mkl_ltcleanup()
 {
-    echo Cleaning...
-    if [[ "$1" == "-l" ]]; then
-        FORTHECHOP="$SUFFIXES"
-    else
-        FORTHECHOP="$SUFFIXES log"
-        echo "(also removing log file)"
-    fi
+	echo Cleaning...
+	if [[ "$1" == "-l" ]]; then
+		FORTHECHOP="$SUFFIXES"
+	else
+		FORTHECHOP="$SUFFIXES log"
+		echo "(also removing log file)"
+	fi
 
-    if [ "$FILE" == "$DIR" ]; then
-        echo ...all tempfiles.
-        for suffix in $FORTHECHOP; do
-            for file in *.$suffix; do
-                [[ -w $file ]] && rm $file
-            done
-        done
-    else
-        echo ...just $FILE tempfiles.
-        for suffix in $FORTHECHOP; do
-            for file in $FILE.$suffix; do
-                [[ -w $file ]] && rm $file
-            done
-        done
-    fi
+	if [ "$FILE" == "$DIR" ]; then
+		echo ...all tempfiles.
+		for suffix in $FORTHECHOP; do
+			for file in *.$suffix; do
+				[[ -w $file ]] && rm $file
+			done
+		done
+	else
+		echo ...just $FILE tempfiles.
+		for suffix in $FORTHECHOP; do
+			for file in $FILE.$suffix; do
+				[[ -w $file ]] && rm $file
+			done
+		done
+	fi
 
-    [[ -w $FILE-blx.bib ]] && rm $FILE-blx.bib  # biblatex
+	[[ -w $FILE-blx.bib ]] && rm $FILE-blx.bib  # biblatex
 
-    return 0
+	return 0
 }
 
 
@@ -225,58 +225,58 @@ function mkl_ltcleanup()
 ##########################################
 
 function mkl_mainwork {
-if [[ $QUIET == 1 ]]; then
-    mkl_docompile > /dev/null
-else
-    mkl_docompile
-fi
+	if [[ $QUIET == 1 ]]; then
+		mkl_docompile > /dev/null
+	else
+		mkl_docompile
+	fi
 
-echo
-if [[ $WASDTX == 1 ]]; then
-    $ECHO -n "(dtx) "
-fi
-echo "Compiled; runing LaCheck..."
-lacheck $FILE
+	echo
+	if [[ $WASDTX == 1 ]]; then
+		$ECHO -n "(dtx) "
+	fi
+	echo "Compiled; runing LaCheck..."
+	lacheck $FILE
 }
 
 if [[ $1 == '-h' ]] || [[ $1 == '--help' ]]; then
-    mkl_usage
+	mkl_usage
 else
-    # Check for quiet mode...
-    if [[ $1 == '-q' ]]; then
-        QUIET=1
-        shift
-    fi
+	# Check for quiet mode...
+	if [[ $1 == '-q' ]]; then
+		QUIET=1
+		shift
+	fi
 
-    FILE=${1:-$DIR}
+	FILE=${1:-$DIR}
 
-    # Check for filename-is-dir shortcut...
-    if [[ $1 == '-k' ]] || [[ $1 == '-l' ]]; then
-        FILE=$DIR
-        KOPT=$1
-    fi
+	# Check for filename-is-dir shortcut...
+	if [[ $1 == '-k' ]] || [[ $1 == '-l' ]]; then
+		FILE=$DIR
+		KOPT=$1
+	fi
 
-    # Remove .tex, .dtx or just . at end of filename...
-    FILE=$(basename -s .tex $FILE)
-    FILE=$(basename -s .dtx $FILE)
-    FILE=$(basename -s . $FILE)
+	# Remove .tex, .dtx or just . at end of filename...
+	FILE=$(basename -s .tex $FILE)
+	FILE=$(basename -s .dtx $FILE)
+	FILE=$(basename -s . $FILE)
 
-    # Check if we're being called as ltcleanup...
-    if [[ $PROGNAME == 'ltcleanup' ]]; then
-        mkl_ltcleanup $KOPT
-        exit $?
-    fi
+	# Check if we're being called as ltcleanup...
+	if [[ $PROGNAME == 'ltcleanup' ]]; then
+		mkl_ltcleanup $KOPT
+		exit $?
+	fi
 
-    # Check for file readability...
-    if [[ ! -r $FILE.tex ]] && [[ ! -r $FILE.dtx ]]; then
-        echo No readable input file specified!
-        mkl_usage
-        exit 42
-    fi
+	# Check for file readability...
+	if [[ ! -r $FILE.tex ]] && [[ ! -r $FILE.dtx ]]; then
+		echo No readable input file specified!
+		mkl_usage
+		exit 42
+	fi
 
-    time mkl_mainwork
+	time mkl_mainwork
 
-    # Coda
-    date
-    exit 0
+	# Coda
+	date
+	exit 0
 fi
