Vim Bindings; Whitespace
* Sort out whitespace in mklatex
* Change _$ and _= to use <leader>
* DRY trailing whitespace removal

diff --git a/bin/mklatex b/bin/mklatex
--- a/bin/mklatex
+++ b/bin/mklatex
@@ -26,11 +26,11 @@ function mkl_checkreturn()
 {
     if [ $? != 0 ]; then
         echo "ERROR!  There has been an error; exiting..."
-		if [ $WASDTX == 1 ]; then
-			lacheck $FILE.dtx
-		else
-			lacheck $FILE
-		fi
+        if [ $WASDTX == 1 ]; then
+            lacheck $FILE.dtx
+        else
+            lacheck $FILE
+        fi
         exit 42
     fi
 }
@@ -40,13 +40,13 @@ function mkl_usage()
     echo "Compile a LaTeX document and/or clean up the results."
     echo
     echo "Usage: mklatex [-q] [<file>.(tex|dtx)] [-k|-l]"
-	echo "    -q     -- ultra-quiet mode (don't use until sure!)"
+    echo "    -q     -- ultra-quiet mode (don't use until sure!)"
     echo "    <file> -- Name of file to compile.  The .tex extension is"
     echo "              not needed.  If not specified, the name of the"
-	echo "              current directory will be used instead."
-	echo "              NB: All files with cleanup suffixes (see below)"
-	echo "                  in the current directory will be removed in"
-	echo "                  this case."
+    echo "              current directory will be used instead."
+    echo "              NB: All files with cleanup suffixes (see below)"
+    echo "                  in the current directory will be removed in"
+    echo "                  this case."
     echo "    -k     -- Keep temporary and log files."
     echo "    -l     -- Keep just the log file."
     echo
@@ -65,13 +65,13 @@ function mkl_docompile_pdflatex()
 {
     if [[ -r $FILE.dtx ]]; then
         pdflatex $FILE.dtx
-		RETVAL=$?
+        RETVAL=$?
         WASDTX=1
     else
         pdflatex $FILE
-		RETVAL=$?
+        RETVAL=$?
     fi
-	return $RETVAL
+    return $RETVAL
 }
 
 function mkl_docompile_mp()
@@ -95,11 +95,11 @@ function mkl_docompile_eps()
     RETVAL=$?
     if [ $RETVAL == 0 ]; then
         for epsfile in *.eps; do
-			if [ ! -f "$(basename -s .eps $epsfile).pdf" ]; then
-				$ECHO -n "$epsfile: " ; epstopdf $epsfile || exit 42 ; echo "done"
-			else
-				echo PDF of $epsfile already exists.
-			fi
+            if [ ! -f "$(basename -s .eps $epsfile).pdf" ]; then
+                $ECHO -n "$epsfile: " ; epstopdf $epsfile || exit 42 ; echo "done"
+            else
+                echo PDF of $epsfile already exists.
+            fi
         done
     else
         echo It seems there are no .eps files here.
@@ -114,51 +114,51 @@ function mkl_docompile()
     mkl_docompile_mp
     echo
     # FIXME remove when get mactex 2009
-	mkl_docompile_eps
+    mkl_docompile_eps
     echo
     echo PDFLaTeX 1
     mkl_docompile_pdflatex
     mkl_checkreturn
     echo
     echo BibTeX
-	# compatible with multibib...
-	for BIBFILE in *.aux ; do 
-		bibtex $(basename $BIBFILE .aux) 
-	done 
+    # compatible with multibib...
+    for BIBFILE in *.aux ; do
+        bibtex $(basename $BIBFILE .aux)
+    done
     if [[ $? != 0 ]]; then
         BIB='false'
     fi
     echo
-	# make glossaries?
-	if [ -r $FILE.glo ]; then
-		echo makeglossaries 1
-		if [ $QUIET == 1 ]; then
-			makeglossaries $FILE 2> /dev/null
-		else
-			makeglossaries $FILE
-		fi
-		mkl_checkreturn
-		echo
-	fi
+    # make glossaries?
+    if [ -r $FILE.glo ]; then
+        echo makeglossaries 1
+        if [ $QUIET == 1 ]; then
+            makeglossaries $FILE 2> /dev/null
+        else
+            makeglossaries $FILE
+        fi
+        mkl_checkreturn
+        echo
+    fi
     echo PDFLaTeX 2
     mkl_docompile_pdflatex > /dev/null
     mkl_checkreturn
-	echo
+    echo
     echo PDFLaTeX 3
     mkl_docompile_pdflatex > /dev/null
     mkl_checkreturn
-	echo
-	# update glossaries and PDF?
-	if [ -r $FILE.glo ]; then
-		echo makeglossaries 2
-		makeglossaries $FILE > /dev/null 2> /dev/null
-		mkl_checkreturn
-		echo
-		echo PDFLaTeX 4
-		mkl_docompile_pdflatex > /dev/null
-		mkl_checkreturn
-		echo
-	fi
+    echo
+    # update glossaries and PDF?
+    if [ -r $FILE.glo ]; then
+        echo makeglossaries 2
+        makeglossaries $FILE > /dev/null 2> /dev/null
+        mkl_checkreturn
+        echo
+        echo PDFLaTeX 4
+        mkl_docompile_pdflatex > /dev/null
+        mkl_checkreturn
+        echo
+    fi
 
     # Errors and warnings...
     if [[ -r $FILE.log ]]; then
@@ -180,7 +180,7 @@ function mkl_docompile()
         fi
         mkl_checkreturn
     fi
-    
+
     # BibTeX failure notice...
     if [[ $BIB == 'false' ]]; then
         echo
@@ -190,29 +190,29 @@ function mkl_docompile()
 
 function mkl_ltcleanup()
 {
-	echo Cleaning...
+    echo Cleaning...
     if [[ "$1" == "-l" ]]; then
         FORTHECHOP="$SUFFIXES"
     else
         FORTHECHOP="$SUFFIXES log"
-		echo "(also removing log file)"
+        echo "(also removing log file)"
     fi
-    
-	if [ "$FILE" == "$DIR" ]; then
-		echo ...all tempfiles.
-		for suffix in $FORTHECHOP; do 
-			for file in *.$suffix; do
-				[[ -w $file ]] && rm $file
-			done
-		done
-	else
-		echo ...just $FILE tempfiles.
-		for suffix in $FORTHECHOP; do 
-			for file in $FILE.$suffix; do
-				[[ -w $file ]] && rm $file
-			done
-		done
-	fi
+
+    if [ "$FILE" == "$DIR" ]; then
+        echo ...all tempfiles.
+        for suffix in $FORTHECHOP; do
+            for file in *.$suffix; do
+                [[ -w $file ]] && rm $file
+            done
+        done
+    else
+        echo ...just $FILE tempfiles.
+        for suffix in $FORTHECHOP; do
+            for file in $FILE.$suffix; do
+                [[ -w $file ]] && rm $file
+            done
+        done
+    fi
 
     [[ -w $FILE-blx.bib ]] && rm $FILE-blx.bib  # biblatex
 
@@ -225,46 +225,46 @@ function mkl_ltcleanup()
 ##########################################
 
 function mkl_mainwork {
-	if [[ $QUIET == 1 ]]; then
-		mkl_docompile > /dev/null
-	else
-		mkl_docompile
-	fi
+if [[ $QUIET == 1 ]]; then
+    mkl_docompile > /dev/null
+else
+    mkl_docompile
+fi
 
-    echo
-    if [[ $WASDTX == 1 ]]; then
-        $ECHO -n "(dtx) "
-    fi
-    echo "Compiled; runing LaCheck..."
-    lacheck $FILE
+echo
+if [[ $WASDTX == 1 ]]; then
+    $ECHO -n "(dtx) "
+fi
+echo "Compiled; runing LaCheck..."
+lacheck $FILE
 }
 
 if [[ $1 == '-h' ]] || [[ $1 == '--help' ]]; then
     mkl_usage
 else
-	# Check for quiet mode...
-	if [[ $1 == '-q' ]]; then
-		QUIET=1
-		shift
-	fi
+    # Check for quiet mode...
+    if [[ $1 == '-q' ]]; then
+        QUIET=1
+        shift
+    fi
 
-	FILE=${1:-$DIR}
+    FILE=${1:-$DIR}
 
     # Check for filename-is-dir shortcut...
     if [[ $1 == '-k' ]] || [[ $1 == '-l' ]]; then
         FILE=$DIR
         KOPT=$1
     fi
- 
-    # Remove .tex, .dtx or just . at end of filename...
-	FILE=$(basename -s .tex $FILE)
-	FILE=$(basename -s .dtx $FILE)
-	FILE=$(basename -s . $FILE)
 
-	# Check if we're being called as ltcleanup...
+    # Remove .tex, .dtx or just . at end of filename...
+    FILE=$(basename -s .tex $FILE)
+    FILE=$(basename -s .dtx $FILE)
+    FILE=$(basename -s . $FILE)
+
+    # Check if we're being called as ltcleanup...
     if [[ $PROGNAME == 'ltcleanup' ]]; then
         mkl_ltcleanup $KOPT
-		exit $?
+        exit $?
     fi
 
     # Check for file readability...
@@ -274,9 +274,9 @@ else
         exit 42
     fi
 
-	time mkl_mainwork
+    time mkl_mainwork
 
-	# Coda
-	date
-	exit 0
+    # Coda
+    date
+    exit 0
 fi
